### ISSUE TITLE
Missing download links from the downloads page

### ISSUE THREAD

**Issue by dopsi** [archlinux32/website#5]
I noticed there is no link to any mirror on the [downloads page](https://archlinux32.org/download/). Shouldn't there be at least a link the one of the mirrors ?

**Comment by tyzoid** [comment]
We have one on the homepage, but this dies appear to be an oversight.

**Comment by deep-42-thought** [comment]
I'll add something to the update-website script which I use to update all the checksums on the download page.

**Comment by deep-42-thought** [comment]
solved by fbefbd6
